### ISSUE TITLE
Enable date format switching

### ISSUE THREAD

**Issue by randrej** [wger-project/wger#1245]
## Use case

When using wger in English, all dates are in the US MM/DD/YYYY format, which I'm not accustomed to as a European.

## Proposal

Either have a field for picking the date format in the settings, or have English US and English UK locales, with appropriate date formats. I could then pick the UK variant.

**Comment by rolandgeider** [comment]
Hi! Sorry for the late reply. I can imagine that this is really annoying! At the moment the application can't support country specific locales, so only "en" and not "en-UK". I haven't looked much into it, because I was always only thinking of the differences in translations which are not important enough for us (and would basically mean doubling the work needed to translate it), not in any of the other country specific localizations and formattings.

**Comment by rolandgeider** [comment]
This is available on master, will update the website these days

**Comment by jpVm5jYYRE1VIKL** [comment]
To be realistic dates still wrong . Issue not fixed. It is using american dates even if changed locale.
