### ISSUE TITLE
Chart missing in "Weight log for workout" page

### ISSUE THREAD

**Issue by AndriiChuzhynov** [wger-project/wger#1308]
## Steps to Reproduce

1. Go to workout log with by URL `/en-gb/workout/log/<workout_id>/view`
2. Observe no chart

But it should be according to description on the page and JS error (see logs)

<details>
  <summary>Logs</summary>

```javascript
Uncaught ReferenceError: wgerDrawWeightLogChart is not defined
    at HTMLDocument.<anonymous> (view:548:21)
    at mightThrow (output.efe1e8a76d0b.js:237:18)
    at process (output.efe1e8a76d0b.js:239:89)
```
</details>

**Comment by Daemonslayer2048** [comment]
I can confirm I have the same issue and same logged error.

**Comment by rolandgeider** [comment]
you are right, there's something missing

**Comment by gmmoraes** [comment]
@rolandgeider , can I work on this task?

**Comment by rolandgeider** [comment]
Hi @gmmoraes sure, go ahead

**Comment by gmmoraes** [comment]
@rolandgeider thanks!

The problem mentioned seems to be a missing import of the `exercises.js` file inside `Template.html` (wger > core > templates > template.html).

`<script src="{% static 'js/exercises.js' %}"></script>`

Adding this import leads to another error
`caught TypeError: E.nest is not a function`

This seems to be happening because the current version of the library `metrics-graphics` currently used is outdated. The method nest_data_for_aggregate_rollover inside metricsgraphics.js is calling d3 `nest()` instead of `group`.

Would you have any suggestions on how to tackle this (sorry I am kind of new to webdev)? Should the version of the `metricsgraphics.js` library be changed to a newer one? (latest versions use typescript)

**Comment by rolandgeider** [comment]
thanks for the analysis. I would say that we try version 3.0.0-beta1 of metrics-graphics (which is already a year old, the whole library is not being developed anymore) and if that fixes the issue, fine, if not then this is a good opportunity to move the chart page to react, which was planned anyway

**Comment by rolandgeider** [comment]
so, I've been cooking up something, it just needs a bit of polishing

![image](https://github.com/wger-project/wger/assets/2280729/7bee5c96-f692-4802-bf98-ba3e93c9a358)
