### ISSUE TITLE
WorkoutLog Dialogue should inherit from Workoutsession

### ISSUE THREAD

**Issue by voszp** [wger-project/wger#132]
For usability reasons the workoutlog dialogue should inherit the number of repeatings and weights from the according workoutsession.

**Comment by rolandgeider** [comment]
Yes, the reason why I still haven't done it is that if all the fields are pre-selected with the repetitions and weights and the user didn't do some of the exercises, in order to avoid logging things he did not do, he'd have to clear all the fields. The timer view has pre-selected data because it's easier to skip them there.

This could be perhaps avoided by having some option to remove whole exercises from the list or  similar.
