### ISSUE TITLE
Request: Additional body parameters

### ISSUE THREAD

**Issue by voszp** [wger-project/wger#133]
Include the opportunity to capture further body parameters like hip size, abdominal girth, chest measurement, girt of upper and lower arms and legs as well as body fat.

**Comment by rolandgeider** [comment]
Tentatively setting this for the 1.7 release.

I have marked this as a feature bug because it probably makes sense to make a new app ("measurements"?) and move the current "weight" one there and that means fun with migrations and imports. This also needs some brain juice to decide what parameters should be logged and how they can be presented to the user (graph, etc.).

**Comment by SvenHinz** [comment]
I would like to see an option to "create" a parameter for myself like this:

Parameter name ---> Text
Parameter unit ---> kg, m, s, number etc.

Like for the weight it would be nice to see a graph.

**Comment by rolandgeider** [comment]
That's a good idea, there could be a list of default parameters, but own ones could be added by the user as well.

**Comment by rolandgeider** [comment]
This is now available on the flutter app, the website will get this a bit later
