### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [wger-project/wger#1371]
## Use case
For some reason the Croatian translation from Weblate https://hosted.weblate.org/languages/hr/wger/ isn't uploaded to the project repository https://github.com/wger-project/wger/tree/master/wger/locale
The Croatian translation is 100 % translated.

## Proposal
Upload the Croatian translation to the project repository https://github.com/wger-project/wger/tree/master

**Comment by rolandgeider** [comment]
ahh, I see where the confusion comes from. The translations in  https://github.com/wger-project/wger/tree/master/wger/locale are the ones from https://hosted.weblate.org/projects/wger/web/ . This is for the django application, but some parts of it are being rewritten in react to be more interactive and those are translated in https://hosted.weblate.org/projects/wger/frontend/ and later copied over to https://github.com/wger-project/wger/tree/master/wger/core/static/react/locales (this process is still a bit manual at the moment so that new translations might not appear immediately there, but there is already an issue for this)

**Comment by rolandgeider** [comment]
(btw, have just added Croatian to weblate)
