### ISSUE TITLE
OpenFoodFacts import broken

### ISSUE THREAD

**Issue by ReadieFur** [wger-project/wger#1393]
## Steps to Reproduce

1. Setup a new instance of WGER (local install, not docker)
2. Download the open food facts dump
3. Run the `merge_open_food_facts.py` script

**Expected results:**
See all entries imported into the WGER database (expected 5,000,000+ results as indicated by the pre-merge setup import to MongoDB)

**Actual results:**
Python script fails to run, import statement invalid (fixed myself)  
The script only imported 6000~ items.

<details>
Enabling some of the logs in the script using the import method I get a lot of invalid name and key errors (missing nutrition key) 
</details>

**Comment by rolandgeider** [comment]
while there are always some ingredients that won't have all the keys, there shouldn't be too many. Also, the script only imports the ones that are marked by OFF as "completed" (this can vary with time because sometimes they introduce new fields that need to be filled in. If you want to import all of them, editl this and just remove the 'complete' part: `for product in db.products.find({'lang': {"$in": list(languages.keys())}, 'complete': 1}):`

That being said, this is a process that at the moment needs too much manual setup and should be automated way more, perhaps with some docker compose or similar
