### ISSUE TITLE
Inconsistent capitalization in exercises.

### ISSUE THREAD

**Issue by ghost** [wger-project/wger#232]
In the exercise list there are all manner of capitalization schemes (or lack thereof). Looks kinda sloppy. I'd suggest doing some formatting when they are submitted.

**Comment by rolandgeider** [comment]
I've tried this on the template (but if we do it it would be necessary to actually save the new name in the database). While the English names look much better, there are a couple of ones in German that look ugly as they have some abbreviations in the name, e.g. "something KH" (Kurzhantel, dumbbell) becomes "Something Kh". I'd need to check if actually writing the whole name out would change any layouts for the worse.

@purplebird do you want to implement this? It would be best to do this using signals, then we make sure that the name is always capitalized

![bildschirmfoto am 2015-11-07 um 10 44 06](https://cloud.githubusercontent.com/assets/2280729/11014588/8350384a-853d-11e5-8517-494c90fdf612.png)

![bildschirmfoto am 2015-11-07 um 10 42 42](https://cloud.githubusercontent.com/assets/2280729/11014589/870fe610-853d-11e5-9c1f-7bb763b35330.png)

**Comment by purplebird** [comment]
@rolandgeider Wouldn't even know where to start...!

**Comment by rolandgeider** [comment]
Adding the bitesize tag because this should be relatively simple to implement. My suggestions:

* For backwards compatibility, add a new field in the exercise model, ``name_original`` or similar
* Add a new migration that copies the current content of ``name`` to it, so we always can get back to the original in case something goes wrong.
* When an exercise is created or saved, a signal takes care of updating the ``name`` field (when creating, the user's input is copied to ``name_original``). For something similar see [e.g. this blog post](http://www.kkabell.com/blog/using-djangos-pre_save-signal/)

As for how to implement a capitalizer, I'd first start with a naive and simple approach (django's is too smart), the python-built-in ``capitalize()`` might be enough.

Also note that the exercise overview is cached, you can clear the cache with ``python manage.py clear-cache --clear-all`` (you might also have to restart the server)

**Comment by rolandgeider** [comment]
Fixed, will update the website one of these days
