### ISSUE TITLE
Add fitbit support.

### ISSUE THREAD

**Issue by Sup3rlativ3** [wger-project/wger#253]
Hi,

Being able to pull in exercise and weight information from fitbit would be fantastic. The upside of intergrating with Fitbit is that they already allow you to import data from places like calorie counter.

https://dev.fitbit.com/docs/

Thanks,
James

**Comment by rolandgeider** [comment]
Fitbit provides an open API, not like myfitnesspal (see #308) that has a closed API. In the beginning we should start with something easy like the body weight and look at food logging once our own is ready (#284). I'd like to move these issues to the top of the TODO list

**Comment by illegalnumbers** [comment]
So I would very much like to see this feature happen, as such I will probably be starting working on it soon. I use Fitbit for calorie burn counting, step counting, sleep counting and weight tracking so I will most likely start with those features since they are things I directly use. Does anyone know of a pip library / Django app that would make this easier?

**Comment by rolandgeider** [comment]
There is working code made by the folks at andela, see e.g. https://github.com/andela/wger_kwach/pull/9 or https://github.com/andela/wger_tpot/pull/7
