### ISSUE TITLE
Should I add one workout or many?

### ISSUE THREAD

**Issue by ktatar156** [wger-project/wger#295]
Hi,
in example I'm working with below plan:
Monday:
1. Deadlift 4x10
2. Pulley machine row 4x10
Friday:
1. Dumbbell lunges 4x10
2. Barbell squats 4x10

How should I use wger software to track that?
Should I add one workout and insert there all 4 exercises or there should be 2 workouts?
If I add them to schedule, they will be active in day of workout (in example in Monday, first one will activate, in Friday second one (I mean when I click 'Start current workout')?
How can I change their names? Because when I add two workouts, all are named 'Workout (2016-06-12)'.

**Comment by rolandgeider** [comment]
You should add one. A workout is basically a weekly routine with as many exercises and training days as you need, where a schedule is a combination of workouts so that it's possible to do more complex routines or programms (e.g. alternating every 2 weeks). You can change the name by editing the workouts.
