### ISSUE TITLE
Project SetUp

### ISSUE THREAD

**Issue by dmigwi** [wger-project/wger#346]
@rolandgeider why did you choose to put a **complicated project setup** on the readme rather than creating a simple bash file that would simplify the work in one line of code(*bash script will contain the project configuration displayed on the readme*).

**Comment by rolandgeider** [comment]
I personally don't like setups that do too much _magic_. Then, there are other problems to think about, the bash file would need to handle some errors during installation, it would only work under some specific configurations (sqlite/postgres, apache/development, debian/centos), etc. On the other hand we could have a script that does the basic setup and leave other, more unusual configurations up to the user.

**Comment by andela-dmigwi** [comment]
To a newbie who is trying out the system, the wger project setup will discourage them a lot. I wholly support the idea of having a simpler way (not necessarily a bash script) to assist anyone do initial project setup, they then can customize the project later on. I and my team members have developed a bash script that is helping us to do wger project set up with the basic settings without much hustle.

**Comment by andela-dmigwi** [comment]
We also made a discovery that wger, has default settings configuration outside the project's root folder, to be specific, the hidden folder (.config) is in my home folder. @rolandgeider i wish the files were only created in the project's root folder, my team and i recommended that we change that, so that all files associated with wger are only in the project's root folder.
Otherwise Wger is an awesome system, its functionality is exceptional.

**Comment by illegalnumbers** [comment]
Did you do the local setup or the docker setup? Personally I found the docker setup to be super simple. There were a couple things on the local setup that were a bit of a hangup for me but that was mostly due to my inexperience with Django.

**Comment by rolandgeider** [comment]
@andela-dmigwi The reason why the configuration files (as well as the sqlite database, etc.) are not in the source folder is that when installing this as a package (``pip install wger``) the source is somewhere else in the system, either in a virtualenv or perhaps even installed system wide, and only the configs are editable by the user. It should also be unproblematic to delete the code as often as needed, similar to when one deletes an application and its configs remain. Since this model isn't very useful during development, I always pass the ``--settings-path`` in the examples and the installation instructions.

**Comment by rolandgeider** [comment]
What are the specific problems you ran into while installing the application? The installation instructions from the README should be easy enough and are only a couple of steps, but if they didn't work or you had otherwise problems, I want to hear about it :)

**Comment by petervanderdoes** [comment]
@rolandgeider I don't think it's very clear what you need to do with the settings path.
The path has to be within the PATH for the app to be able to import the settings module. I think for the average user this is not clear.

Maybe it's better to just remove the `settings-path` parameter and always install the settings file in it's default location, being `~/.config/wger` on Linux/*BSD or APP-PATH on Windows.

**Comment by teaglebuilt** [comment]
When I run the server it says there is no module named settings. I am using the git instructions. I clearly dont understand whats next

**Comment by rolandgeider** [comment]
create-settings now puts the settings file in the source folder by default and should take care of most of the problems during installation. Closing this issue now
