### ISSUE TITLE
What exactly does the "order" number mean?

### ISSUE THREAD

**Issue by MLenthousiast** [wger-project/wger#376]
I'm new to Github, so I am not sure if this is the rigth way of asking these kind of questions, but:

What exactly does the order field (in for example the Setting table) entail? Mostly it returns 1 in the cases I have seen, does it mean the fields are sorted by the first column? Or something else?

**Comment by rolandgeider** [comment]
Don't worry, opening an issue to ask about some implementation detail is OK.

As for the order field, it is used for ordering. You might be seeing a lot of 1s because some of the order fields are only used in certain cases e.g. for supersets, i.e. if there is more than one exercise per set. However it is also possible that I added an order field to tables that later were sorted by another column.

I'm closing the issue, but feel free to answer here or reopen it
