### ISSUE TITLE
Page 403 Error As Admin in any User / Gym account edit

### ISSUE THREAD

**Issue by kuggaa** [wger-project/wger#401]
howban dot win

We lauched WGER as a kids sports tool for Teams to track workouts.

Upon admin login at any (en/user/33/overview | en/gym/2/members) editing creates page 403 error.

Details
en/gym/export/users/2   error 403

Gym configuration
Edit error 403
CONTRACTS
en/gym/contract-type/list/2
add error 403
edit error 403

OPTIONS
en/gym/contract-option/list/2
error 403

Roles /edit user
Error 403

You don't have authorization to view this page.
HTTP ERROR 403

Logged in as ADMIN

SUPER USER SETTING AVAILABLE ADMIN OR USER?

FYI We intend to sell advertisements on site to fund lowincome kids in sports....great product.
Just built first Django webserver....yikes.

**Comment by rolandgeider** [comment]
Great that you like the software!

Did you have always problems accessing those pages or did it suddenly 
start? I'd have to check because I don't remember exactly, but only Gym 
Administrators (i.e. *not* the default admin user) are allowed to access 
the overviews and gym member pages. But as I said, I'm not completely sure.

Am 15.07.2017 um 23:58 schrieb Kuggaa Cuckoo Choo Choo:
> howban dot win
> 
> We lauched WGER as a kids sports tool for Teams to track workouts.
> 
> Upon admin login at any (en/user/33/overview | en/gym/2/members) editing 
> creates page 403 error.
> 
> Details
> en/gym/export/users/2 error 403
> 
> Gym configuration
> Edit error 403
> CONTRACTS
> en/gym/contract-type/list/2
> add error 403
> edit error 403
> 
> OPTIONS
> en/gym/contract-option/list/2
> error 403
> 
> Roles /edit user
> Error 403
> 
> You don't have authorization to view this page.
> HTTP ERROR 403
> 
> Logged in as ADMIN
> 
> SUPER USER SETTING AVAILABLE ADMIN OR USER?
> 
> FYI We intend to sell advertisements on site to fund lowincome kids in 
> sports....great product.
> Just built first Django webserver....yikes.

Well, that's only for development! :D

If you want to really use this, take a look here: 
https://wger.readthedocs.io/en/latest/production.html
