### ISSUE TITLE
Restarting Docker container

### ISSUE THREAD

**Issue by ghost** [wger-project/wger#414]
Hello,

I have deployed the Docker image to a server with the following command:

`
docker run -ti --name wger.apache --publish 8000:80 wger/apache
`

My problem is if the container stops for a reason I cannot restart it. I've tried:

`
docker start {container id} -a -i
`

When I run the command above, I get this error:

> /usr/sbin/apache2ctl: 87: ulimit: error setting limit (Operation not permitted)
> Setting ulimit failed. See README.Debian for more information.
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
> httpd (pid 6) already running

Does anyone know a way of restarting the existing container?

Thanks.

**Comment by volkanx** [comment]
I've found the solution here: https://stackoverflow.com/questions/28654076/docker-container-wont-start-because-an-existing-pid-file

I'll leave it instead of deleting the question in case it helps other people in the future.

This worked to start an existing container:

`docker start [container_id]; docker exec [container_id] rm /run/apache2/apache2.pid`
