### ISSUE TITLE
Integration with "Open Food Facts"

### ISSUE THREAD

**Issue by Anth0rx** [wger-project/wger#422]
Wouldn't it be nice, if wger integrated with [Open Food Facts](https://world.openfoodfacts.org/)?

**Comment by teolemon** [comment]
Yes it would :-) 👍

**Comment by Anth0rx** [comment]
Are you already planning to do this?

**Comment by teolemon** [comment]
Nope, I was just notified by a contributor, since I'm one of the Open Food Facts admins :)

**Comment by rolandgeider** [comment]
This sounds really nice, how come I never found this? :smile: I'll definitely have to take a look

**Comment by Anth0rx** [comment]
They also have a "Nutri-Score", Nutrition facts and descriptions with ingredients for most foods :)

**Comment by EmilAlipiev** [comment]
is there an api or open database for it?

**Comment by teolemon** [comment]
yup and yup
en.wiki.openfoodfacts.org/API
world.openfoodfacts.org/data

**Comment by EmilAlipiev** [comment]
@teolemon when I search https://world.openfoodfacts.org/cgi/search.pl?search_terms=water&search_simple=1&json=1&page=1 

why results are mostly in french although i am searching an english term? 

another question does your api use like elasticsearch or simple free text search? it seems to me that it is free text search. will you be willing to improve it using elasticsearch. i would like to implement it for you to get better results with suggestions

**Comment by rolandgeider** [comment]
there's even a python wrapper around the api

https://github.com/openfoodfacts/openfoodfacts-python

This should be definitely one of the next bigger things to do

**Comment by harlenesamra** [comment]
My team will try to begin work on this and will follow up with questions since this is more of an open discussion!

**Comment by rolandgeider** [comment]
Some thoughts...

New Fields/Models:
- some kind of source ID that identifies the ingredient at the provider since the id is only local. Most of the existing exercises in English are from a list from the US Department of Agriculture and because I lost the repo with the import script, now I have no way of safely updating them... Never again!
- Source name (open food data, etc.)
- Source URL (link to product page / REST endpoint)
- Datetime last imported / updated
- common name vs. name (?)
- Images
- Categories (make it similar to exercises with a central category that has a translatable attribute that points to the language specific translations?)
- Vegetarian/Vegan/etc tags (these seem to be calculated automatically based on the ingredient lists so not all ingredients have them. How many?)
- Brand (probably useful)
- Micronutrients (probably not, but possibly somehting for the future)

TODO:
- update models
- import script for the initial import and update
- the search bar could be updated as well (e.g. only search beverages, etc, but this is not necessary ATM)

Questions:
- How to import this? The mongo dump is 2,5GB compressed and 16GB uncompressed... (are images even included here? Probably not) Querying the API might take too long. If with mongo, make a docker for this.
- If the ingredient list becomes too big, it won't be feasible to save them all in a json file that just makes the checkout unecessarily huge. Perhaps move this to a new data repo? Compress the json? This would reduce the size but would make diffs impossible. On the other hand, if the file is generated anyway and nobody can spot errors or anything in a diff anyway.
- Import ingredients and map country to language used in the application (Germany, Austria -> de, etc.) In the beginning just do a few and if everything works fine, this can be expanded
- Can products deleted from open food facts be recognized and removed here as well?


Philosophical questions
- What to do if there are too many ingredients? If I can't find what I need this might be less useful than if there were too few. Perhaps only import the products with an image, since those are probably the ones most used (or perhaps the API even has somethings like a completeness value)

**Comment by rolandgeider** [comment]
Note to self, the images are not in the mongo db dump, but their URL can be calculated: e.g. for product 4000417281005 you get in the results a huge array under 'images'

```python
[...]
'front_de': {'angle': 0,
             'geometry': '0x0--1--1',
             'imgid': 12,
             'normalize': None,
             'rev': 38,
             'sizes': {'100': {'h': 81, 'w': 100},
                       '200': {'h': 162, 'w': 200},
                       '400': {'h': 323, 'w': 400},
                       'full': {'h': 386, 'w': 478}},
                       'white_magic': None,
                       'x1': -1,
                       'x2': -1,
                       'y1': -1,
                       'y2': -1},
'ingredients_cs': {'angle': '0',
                   'geometry': '1328x369-109-272',
                   'imgid': '11',
                   'normalize': 'false',
                   'rev': '34',
                   'sizes': {'100': {'h': 28, 'w': 100},
                             '200': {'h': 56, 'w': 200},
                             '400': {'h': 111, 'w': 400},
                             'full': {'h': 369, 'w': 1328}},
                             'white_magic': 'false',
                             'x1': '109.35843481939149',
                             'x2': '1437.2351047597854',
                             'y1': '272.18381250914365',
                             'y2': '641.2497976667208'},
[...]
```
from that you construct the image URL like this: https://static.openfoodfacts.org/images/products/400/041/728/1005/front_de.39.full.jpg

and it seems that the front_xyz (or just front) are the front pictures

**Comment by hangy** [comment]
> Note to self, the images are not in the mongo db dump, but their URL can be calculated: e.g. for product 4000417281005 you get in the results a huge array under 'images'
> 
> and it seems that the front_xyz (or just front) are the front pictures

Note that each image may be available in more than one language, and the [internal structure](https://github.com/openfoodfacts/openfoodfacts-server/blob/8ced35af7e9546e1dd7bf1eaa5c62cdcab3264c7/lib/ProductOpener/Display.pm#L10159-L10216) might change at some point in time. The REST API should contain the relevant image for each product, see https://wiki.openfoodfacts.org/index.php?title=API/Read/Product&oldid=8712#Product_images. 🙂

**Comment by rolandgeider** [comment]
You are right, but they also write that the API shouldn't be used to scrape the db so I wanted to do as much as possible locally with the data from the dump

**Comment by rolandgeider** [comment]
Basic import seems to be working, closing this issue
