### ISSUE TITLE
Integrity error when adding weight entries

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#560]
When adding weight entries via the REST API (`/api/v2/weightentry/` ), it is possible to generate an integrity error on the DB if the user tries to add two weight entries for the same date. While this is defined in the weight model, it seems Django Rest Framework doesn't use the information.

**Comment by sandilsranasinghe** [comment]
Uh there is a unique_together in the class meta for user and date
```unique_together = ("date", "user")```
Was it initially intended to allow only one weight entry per day per user?

**Comment by rolandgeider** [comment]
Yeah. When trying to add a second weight to a date in the application, the form shows a regular error, but when adding it via the API, there's an internal server exception

**Comment by sandilsranasinghe** [comment]
It seems in the case of the form the ModelForms unique_together validator raises a validation error.

However for the API, since in the corresponding Serializer the user field is excluded, it appears that the serializer ignores that field in validation

```
class WeightEntrySerializer(serializers.ModelSerializer):
    """
    Weight serializer
    """
    class Meta:
        model = WeightEntry
        exclude = ('user',)
```
If the user field is excluded purely because it must be added from the requests user and not the form, perhaps something like this might work, from the drf [documentation](https://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields)

> Note: There is a special-case where a read-only field is part of a unique_together constraint at the model level. In this case the field is required by the serializer class in order to validate the constraint, but should also not be editable by the user.

> The right way to deal with this is to specify the field explicitly on the serializer, providing both the read_only=True and default=… keyword arguments.

> One example of this is a read-only relation to the currently authenticated User which is unique_together with another identifier. In this case you would declare the user field like so:

So something like this raises a regular error,

```
class WeightEntrySerializer(serializers.ModelSerializer):
    """
    Weight serializer
    """
    user = serializers.PrimaryKeyRelatedField(read_only=True, default=serializers.CurrentUserDefault())
    class Meta:
        model = WeightEntry
        # exclude = ('user',)
        fields = '__all__'
```
the error being,
```
{
  "non_field_errors": [
    "The fields date, user must make a unique set."
  ]
}
```

Would that be okay?

**Comment by rolandgeider** [comment]
That would be great!

**Comment by rolandgeider** [comment]
I just deployed this fix. BTW, WorkoutSession also has a unique_together with the user and the date. Do you want to fix that one as well?

**Comment by sandilsranasinghe** [comment]
Sure. I'll add a commit for that too :)
