### ISSUE TITLE
Body weight overview breaks after ~556 entries

### ISSUE THREAD

**Issue by dugite-code** [wger-project/wger#954]
## Steps to Reproduce

1. Mass import (> 556 entries) body weight data via csv
2. Interface will say it can't convert some of the entries
3. Imported entries will show in body weight overview and dashboard as expected
4. Attempt to add more entries either via import or the add entry dialogue.

**Expected results:**
New body weight entries should be viewable/editable in the overview page.

**Actual results:**
Import/addition appears to work but only shows on the dashboard but not the overview meaning editing/manipulating new entries is impossible. Overview page appears to be limited to 50 pages.

Unfortunately There appears to be no relevant Logs.

I realize my attempted use case was a little ridiculous. I have body weight records dating back to 2012 thanks to a Bluetooth scale I hooked up to my server.

On a side note, know how I can mass delete the entries? or should I just blow away the data volumes and start again?

**Comment by rolandgeider** [comment]
Hi!

As it turns out, we're currently working on the weight module, so this might get auto fixed soon. Can you take a look at `/api/v2/weightentry/` and see how many entries managed to get to the DB?

At the moment there is no way to mass delete entries, you don't need do delete all the volumes, you can just connect to the DB and delete it there with one command (but if you have no data nuking the volumes might be the fastest way)

**Comment by dugite-code** [comment]
Looks like the entry's are getting added when querying the API so it must just be a front end issue.

I'll just do a nuke and pave, was still in the set-up phase so no major loss to do it the quick and easy way

**Comment by rolandgeider** [comment]
You are right, the frontend only loads the first 500 entries. We'll bump this to 999 the next week or so which is probably enough for most cases but there's another issue open which would load all entries by iterating over the paginated results

**Comment by rolandgeider** [comment]
Closing here
