### ISSUE TITLE
Checkboxs for weekdays on "Add exercises to this workout day" popup modal don't seem to save.

### ISSUE THREAD

**Issue by Wartz** [wger-project/wger#974]
## Steps to Reproduce

1. wger 2.1-dev docker image (pulled around 30 hrs ago)
2. Create a workout (Training menu -> Workouts, then click on Add a Workout button)
3. Click **Add a training day**
4. On the modal, enter a name, select one or more check boxes for days of the week and click Save.

**Expected results:** 
Clicking Save on the Add a Training Day popup modal after setting required information (Name, day of the week) immediately saves the workout day and redirects me back to the workout page.

**Actual results:** 
The modal switches to a full screen view, and alerts me that selecting one or more days is required.
Once on the full screen view, selecting a day of the week checkbox and clicking save works correctly and the workout day is saved.

<details>
  <summary>Logs from docker logs <container name></summary>

From docker_web
```bash
DEBUG 2022-02-24 07:32:11,469 generic_views <ul class="errorlist"><li>day<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
```
From docker_ngnix
```docker
<Server IP> - -[24/Feb/2022:12:32:11 +0000] "POST /en/workout/day/21/day/add HTTP/1.1" 200 26532 "https://domain.tld/en/workout/21/view" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0" "<Client IP>"
```

</details>

![image](https://user-images.githubusercontent.com/218979/155525645-15677820-3fa8-4517-8ede-31a86a39ad85.png)
![image](https://user-images.githubusercontent.com/218979/155525689-56b9f0d2-b2ea-4893-864e-c376a20ef9cf.png)

**Comment by mattcen** [comment]
I just had a quick look at the HTML code for this, and while I haven't had a chance to test it yet, my guess at the issue is that the day inputs are not actually part of the form.
When the form gets downloaded by jQuery from `/en/workout/day/1/day/add`, the raw code looks fine, but when it gets inserted into the web page as a modal, it appears that (looking at the code using the web inspector) the list of days gets moved *outside* the form element and inserted below it. This is hinted at by the fact that they are below the Save button, too. I'm not sure how the code that does this works, so am not in a good position to send a PR, unfortunately.
